name: joycaption
channels:
  - conda-forge            # pytorch-gpu meta-package lives here
  - pytorch                # authoritative CUDA wheels for PT 2.7
dependencies:
  # ─ GPU PyTorch stack (CUDA 12.4) ─
  - pytorch-gpu = 2.7.*
  - torchvision = 0.20.*       # ← explicit, GPU build
  - torchaudio = 2.7.*
  # (pytorch-cuda 12.4 gets pulled automatically)

  # misc native deps
  - python = 3.11.9
  - timm
  - safetensors
  - pillow
  - matplotlib

  # ─ HF / Gradio stack ─
  - pip
  - pip:
      - gradio>=4.24
      - huggingface_hub
      - transformers==4.51.0
      - accelerate
      - sentencepiece
